CREATE TABLE [dbo].[ITEM_FACT] (
    [Item_ID] VARCHAR (4)  NOT NULL,
    [TICKER]  VARCHAR (10) NOT NULL,
    [YEAR]    INT          NOT NULL,
    [Value]   BIGINT       NULL,
    PRIMARY KEY CLUSTERED ([YEAR] ASC, [Item_ID] ASC, [TICKER] ASC),
    FOREIGN KEY ([Item_ID]) REFERENCES [dbo].[ITEM_SETTING] ([Item_ID]),
    FOREIGN KEY ([TICKER]) REFERENCES [dbo].[COMPANY_INFO] ([Company_Ticker])
);